apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-app
  labels:
    app: new-app
spec:
  selector:
    matchLabels:
      app: new-app
  template:
    metadata:
      labels:
        app: new-app
    spec:
      containers:
        - name: new-app
          image: new-app-image
          ports:
            - containerPort: 3000